### ISSUE TITLE
cross-endian gobject-introspection

### ISSUE THREAD

**Issue by q66** [void-ppc/void-packages#10]
`xbps-src` includes some infra for handling gobject-introspection in cross, however it does not seem to be enough, as when cross compiling from little endian to big endian the compiler call in `g-ir-scanner` fails.

I have debugged this a bit and found the cause - the implementation of `g-ir-scanner` changes `LD_LIBRARY_PATH` and with our cross setup the first library path in there is for the cross base, which results in a failed call of a native executable.

This is also likely the reason why these fail on `musl`.

I'm trying to patch `g-ir-scanner` appropriately and it seems like it's possible, just a little bit tricky.

@pullmoll

**Comment by pullmoll** [comment]
Hey, good catch! I already played with `LD_LIBRARY_PATH` in the `gobject-introspection` helper scripts but did not get it working. If you can manage to fix it for cross endian I also think it should fix musl, and this will make @maxice8 happy methinks.

**Comment by maxice8** [comment]
On Sat, Apr 27, 2019 at 11:32:02AM -0700, Jürgen Buchmüller wrote:
> Hey, good catch! I already played with `LD_LIBRARY_PATH` in the `gobject-introspection` helper scripts but did not get it working. If you can manage to fix it for cross endian I also think it should fix musl, and this will make @maxice8 happy methinks.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-ppc64/void-packages/issues/10#issuecomment-487309251

It would make me very happy yeah but i'm not on Void anymore

**Comment by q66** [comment]
I have a fix ready for submission now.

**Comment by q66** [comment]
```
=> Registering new packages to /host/binpkgs/be
index: added `atk-2.32.0_1' (ppc64).
index: added `atk-devel-2.32.0_1' (ppc64).
index: 343 packages registered.
=> Registering new packages to /host/binpkgs/be/debug
index: added `atk-dbg-2.32.0_1' (ppc64).
index: 218 packages registered.
=> Registering new packages to /host/binpkgs/be
index: added `gdk-pixbuf-2.38.1_1' (ppc64).
index: added `gdk-pixbuf-devel-2.38.1_1' (ppc64).
index: added `gdk-pixbuf-xlib-2.38.1_1' (ppc64).
index: 346 packages registered.
=> Registering new packages to /host/binpkgs/be/debug
index: added `gdk-pixbuf-dbg-2.38.1_1' (ppc64).
index: added `gdk-pixbuf-devel-dbg-2.38.1_1' (ppc64).
index: added `gdk-pixbuf-xlib-dbg-2.38.1_1' (ppc64).
index: 221 packages registered.
```

**Comment by q66** [comment]
fixed
