### ISSUE TITLE
qt5: cross building for ppc64 from x86_64 fails

### ISSUE THREAD

**Issue by pullmoll** [void-ppc/void-packages#20]
I see two things when trying to cross build qt5 from my x86_64 environment. First, the build fails once because of what seems like a parallelism issue:
```
moc Private/qquicktreemodeladaptor_p.h
compiling extensions/qwaylandxdgshellv6integration.cpp
moc qquickpane_p.h
linking ../../../bin/qhelpgenerator
powerpc64-linux-gnu-g++: error: /builddir/qt-everywhere-src-5.13.0/qttools/lib/libQt5Help.so: No such file o
r directory
make[4]: *** [Makefile:102: ../../../bin/qhelpgenerator] Error 1
```

Since the `do_build()` function calls make twice, it continues, finds the `libQt5Help.so` the next time round, until later an error in `qtwebengine` at `[8420/15568]` occurs where it tries to build an object file with the native `g++` yet with the `CXXFLAGS` containing `-maltivec` and `-mvsx`?
```
[8420/15568] CXX v8_snapshot/obj/v8/torque_base/torque_base_jumbo_1.o
FAILED: v8_snapshot/obj/v8/torque_base/torque_base_jumbo_1.o
/usr/lib/ccache/bin/g++ -MMD -MF v8_snapshot/obj/v8/torque_base/torque_base_jumbo_1.o.d -DUSE_UDEV -DUSE_AUR
A=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DNO_TCMALLOC -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DTOOLKIT_QT -D_FILE_OFF
SET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEB
UG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DV8_D
EPRECATION_WARNINGS -DV8_INTL_SUPPORT -DV8_CONCURRENT_MARKING -DV8_EMBEDDED_BUILTINS -DV8_TARGET_ARCH_PPC -D
V8_TARGET_ARCH_PPC64 -DV8_TARGET_ARCH_PPC_LE -DDISABLE_UNTRUSTED_CODE_MITIGATIONS -I. -Iv8_snapshot/gen -I..
/../3rdparty/chromium -I../../3rdparty/chromium/v8 -Iv8_snapshot/gen/v8 -fno-strict-aliasing --param=ssp-buf
fer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SO
URCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-d
angling-else -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-p
ointer -g0 -fvisibility=hidden -mcpu=power8 -maltivec -mvsx -Wno-strict-overflow -Wno-return-type -O3 -fno-i
dent -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-attributes -Wno-class-memaccess -W
no-subobject-linkage -Wno-invalid-offsetof -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c v8_snaps
hot/gen/v8/torque_base_jumbo_1.cc -o v8_snapshot/obj/v8/torque_base/torque_base_jumbo_1.o
g++: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
g++: error: unrecognized command line option '-maltivec'
g++: error: unrecognized command line option '-mvsx'
```

I assume the build went fine on `ppc64le` and have no idea why it fails here...

**Comment by q66** [comment]
hm, not sure if i can help with that - i crosscompiled qt5 from ppc64le to ppc64 (incl. musl) before and it worked for me...

**Comment by q66** [comment]
I have an idea about the cross build. It seems that when building v8 snapshot, the cross `CXXFLAGS` leak in when building a host thing. Right now, there's this code in the qt5 template:

```
		case "$XBPS_TARGET_MACHINE" in
		arm*|mips*)
			if [ "$build_option_webengine" ]; then
				# V8 snapshot can't be built with a 64 bit host compiler
				opts+=" -no-webengine-v8-snapshot"
			fi
			;;
		esac
```

I suspect it's precisely because of this issue, and the `-no-webengine-v8-snapshot` should be added unconditionally when cross compiling...

so maybe just remove the `case` and add it directly to `opts`, that whole block is already contained in `if [ "$CROSS_BUILD" ]`

**Comment by q66** [comment]
I think the only reason `aarch64` does not look affected is because its flags are seemingly compatible, doesn't mean it's right though. We should remove the `case` and bump `qt5`. (also, don't forget to remove the misleading comment, it's not about 64-bit host compiler, it's about flags conflicts)

**Comment by q66** [comment]
Alternatively, we could try patching `v8` to erase those flags from host tools, and then we could enable v8 snapshot for all (maybe patch it to use `$CXXFLAGS_host` instead, to get our hardening options and stuff on it while at it)

**Comment by pullmoll** [comment]
I'd rather not bump qt5 (yet) because the official builders are not involved.
I'm trying to get it built here this or that way and have already tried, yet without success so far.

**Comment by q66** [comment]
If we change cross build settings then official builders will be involved (because of ARM)

**Comment by pullmoll** [comment]
Sure, that's why I edited my comment and inserted *(yet)* :) I'll give it a try with unconditional `-no-webengine-v8-snapshot` first.

**Comment by pullmoll** [comment]
I still see the same error so it's not related to `-webengine-v8-snapshort` or `-no-webengine-v8-snapshot`. For now trying to cross build without `webengine` option.

**Comment by q66** [comment]
big endian webengine was dropped and webengine itself is now split off, if the issue still happens for ppc64le we can open a new one later
