### ISSUE TITLE
dracut: add a module to properly handle loading of Power Mac windfarm modules early in initramfs

### ISSUE THREAD

**Issue by q66** [void-ppc/void-packages#21]
I wrote such hook and create a PR in Dracut upstream: https://github.com/dracutdevs/dracut/pull/610

This works great on my G5 `PowerMac11,2`, but could use wider testing. The easiest way is to create a `90ppcmac` directory in your `/usr/lib/dracut/modules.d` and paste the two files from the PR in there, then rebuild your initramfs.

@pullmoll @stenstorp

**Comment by pullmoll** [comment]
I updated dracut here to install the two files into `/usr/lib/dracut/modules.d/90ppcmac` and all seems to work. I'm also going to test the [new ISOs](https://repo.voidlinux.de/live) created with the patched dracut soon.

Oh, I also have a PowerMac11,2 and a PowerBook G4 which identifies as Powerbook3,3.

**Comment by q66** [comment]
Yeah, I'm not expecting any problems with these. I'd still like to have this upstreamed though so I'm waiting for input from the `dracut` devs to see if there's something that needs to be changed for upstreaming, before patching it into our `dracut` package until a new release is made.

**Comment by ernsteiswuerfel** [comment]
Just tested pullmolls new ppc64 iso. Works like a charm now on my G5 7,3! It selectively loads windfarm_pm7,2 and necessary deps. Thanks!

**Comment by pullmoll** [comment]
@ernsteiswuerfel There's a bug left in the install script, though. You cannot install grub unless you change a line in `/usr/bin/void-installer` which has `>$log` to `>$LOG`. I'll create some new ISOs in the next days.

**Comment by q66** [comment]
What do you mean? I fixed this problem ages ago in our void-mklive.

**Comment by ernsteiswuerfel** [comment]
> @ernsteiswuerfel There's a bug left in the install script, though. You cannot install grub unless you change a line in `/usr/bin/void-installer` which has `>$log` to `>$LOG`. I'll create some new ISOs in the next days.

I did only boot the .iso to test if the windfarm module gets loaded now automatically. I didn't try to install (did this with an earlier iso).

**Comment by pullmoll** [comment]
@q66 sure, but I hadn't updated my copy of void-mklive on the G5 where I built the ISOs. My fault. D'OH!

**Comment by q66** [comment]
waiting for upstream to do a review has proven to be a futile effort so speeding this up https://github.com/void-linux/void-packages/pull/14092
