### ISSUE TITLE
nodejs 12.x does not build on 32-bit ppc

### ISSUE THREAD

**Issue by q66** [void-ppc/void-packages#27]
This is a big problem for e.g. Firefox (for now we can switch it to `nodejs-lts`, but that won't work forever).

**Comment by q66** [comment]
This will apparently not be fixed. We can for now stick with 10 which is supported for a couple years more.

**Comment by thosoo** [comment]
There has been a patchset posted here nodejs/node#30323, maybe this could help make nodejs-lts work on 32 bit again
