### ISSUE TITLE
Xorg locks up with radeon driver with hardware acceleration disabled

### ISSUE THREAD

**Issue by nicolascolla** [void-ppc/void-packages#36]
System: Void Linux PPC (glibc version)

Package: xf86-video-ati-19.1.0_1

When disabling hardware acceleration in the xorg configuration file with the line "Option "Accel" "false"", Xorg refuses to start. After running "startx", the screen locks up after showing some Xorg messages and the user is unable to change to another tty, leaving the system unusable without a hard reboot. This has been tried with numerous window managers, with the same results

Disabling hardware acceleration is vital for those using iBook G3s, since an infamous Radeon bug already makes it impossible to run any modern version of xorg with acceleration enabled.

**Comment by nicolascolla** [comment]
These are the contents of my Xorg log file:

[  1387.859] 
X.Org X Server 1.20.6
X Protocol Version 11, Revision 0
[  1387.865] Build Operating System: Linux Void
[  1387.868] Current Operating System: Linux iBookG3 5.3.16_1 #1 SMP Sat Dec 14 04:28:11 UTC 2019 ppc
[  1387.869] Kernel command line: BOOT_IMAGE=/boot/vmlinux-5.3.16_1 root=UUID=db3c1081-d7f9-4e56-b8eb-f4063cdfebf9 ro loglevel=4 slub_debug=P page_poison=1
[  1387.880] Build Date: 08 December 2019  06:20:23PM
[  1387.884]  
[  1387.889] Current version of pixman: 0.38.4
[  1387.899] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  1387.900] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1387.925] (==) Log file: "/var/log/Xorg.1.log", Time: Tue Dec 17 08:57:57 2019
[  1387.935] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1387.937] (==) No Layout section.  Using the first Screen section.
[  1387.938] (==) No screen section available. Using defaults.
[  1387.938] (**) |-->Screen "Default Screen Section" (0)
[  1387.938] (**) |   |-->Monitor "<default monitor>"
[  1387.939] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  1387.939] (==) Automatically adding devices
[  1387.939] (==) Automatically enabling devices
[  1387.939] (==) Automatically adding GPU devices
[  1387.939] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1387.940] (WW) The directory "/usr/share/fonts/X11/OTF" does not exist.
[  1387.940] 	Entry deleted from font path.
[  1387.940] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/TTF,
	/usr/share/fonts/X11/Type1,
	/usr/share/fonts/X11/100dpi,
	/usr/share/fonts/X11/75dpi
[  1387.940] (==) ModulePath set to "/usr/lib/xorg/modules"
[  1387.940] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1387.940] (II) Module ABI versions:
[  1387.940] 	X.Org ANSI C Emulation: 0.4
[  1387.941] 	X.Org Video Driver: 24.0
[  1387.941] 	X.Org XInput driver : 24.1
[  1387.941] 	X.Org Server Extension : 10.0
[  1387.943] (II) xfree86: Adding drm device (/dev/dri/card0)
[  1387.955] (--) PCI:*(0@0:16:0) 1002:4c57:1002:4c57 rev 0, Mem @ 0x98000000/134217728, 0x90000000/65536, I/O @ 0x00000400/256, BIOS @ 0x????????/131072
[  1387.956] (II) LoadModule: "glx"
[  1387.958] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1388.026] (II) Module glx: vendor="X.Org Foundation"
[  1388.026] 	compiled for 1.20.6, module version = 1.0.0
[  1388.026] 	ABI class: X.Org Server Extension, version 10.0
[  1388.027] (II) Applying OutputClass "Radeon" to /dev/dri/card0
[  1388.027] 	loading driver: radeon
[  1388.027] (==) Matched radeon as autoconfigured driver 0
[  1388.027] (==) Matched fglrx as autoconfigured driver 1
[  1388.027] (==) Matched ati as autoconfigured driver 2
[  1388.027] (==) Matched modesetting as autoconfigured driver 3
[  1388.027] (==) Matched fbdev as autoconfigured driver 4
[  1388.027] (==) Assigned the driver to the xf86ConfigLayout
[  1388.027] (II) LoadModule: "radeon"
[  1388.029] (II) Loading /usr/lib/xorg/modules/drivers/radeon_drv.so
[  1388.034] (II) Module radeon: vendor="X.Org Foundation"
[  1388.035] 	compiled for 1.20.5, module version = 19.1.0
[  1388.035] 	Module class: X.Org Video Driver
[  1388.035] 	ABI class: X.Org Video Driver, version 24.0
[  1388.035] (II) LoadModule: "fglrx"
[  1388.038] (WW) Warning, couldn't open module fglrx
[  1388.038] (EE) Failed to load module "fglrx" (module does not exist, 0)
[  1388.038] (II) LoadModule: "ati"
[  1388.039] (II) Loading /usr/lib/xorg/modules/drivers/ati_drv.so
[  1388.039] (II) Module ati: vendor="X.Org Foundation"
[  1388.040] 	compiled for 1.20.5, module version = 19.1.0
[  1388.040] 	Module class: X.Org Video Driver
[  1388.040] 	ABI class: X.Org Video Driver, version 24.0
[  1388.041] (II) LoadModule: "modesetting"
[  1388.042] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1388.043] (II) Module modesetting: vendor="X.Org Foundation"
[  1388.043] 	compiled for 1.20.6, module version = 1.20.6
[  1388.043] 	Module class: X.Org Video Driver
[  1388.043] 	ABI class: X.Org Video Driver, version 24.0
[  1388.043] (II) LoadModule: "fbdev"
[  1388.046] (WW) Warning, couldn't open module fbdev
[  1388.046] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1388.046] (II) RADEON: Driver for ATI/AMD Radeon chipsets:
	ATI Radeon Mobility X600 (M24), ATI FireMV 2400,
	ATI Radeon Mobility X300 (M24), ATI FireGL M24 GL,
	ATI Radeon X600 (RV380), ATI FireGL V3200 (RV380),
	ATI Radeon IGP320 (A3), ATI Radeon IGP330/340/350 (A4),
	ATI Radeon 9500, ATI Radeon 9600TX, ATI FireGL Z1, ATI Radeon 9800SE,
	ATI Radeon 9800, ATI FireGL X2, ATI Radeon 9600, ATI Radeon 9600SE,
	ATI Radeon 9600XT, ATI FireGL T2, ATI Radeon 9650, ATI FireGL RV360,
	ATI Radeon 7000 IGP (A4+), ATI Radeon 8500 AIW,
	ATI Radeon IGP320M (U1), ATI Radeon IGP330M/340M/350M (U2),
	ATI Radeon Mobility 7000 IGP, ATI Radeon 9000/PRO, ATI Radeon 9000,
	ATI Radeon X800 (R420), ATI Radeon X800PRO (R420),
	ATI Radeon X800SE (R420), ATI FireGL X3 (R420),
	ATI Radeon Mobility 9800 (M18), ATI Radeon X800 SE (R420),
	ATI Radeon X800XT (R420), ATI Radeon X800 VE (R420),
	ATI Radeon X850 (R480), ATI Radeon X850 XT (R480),
	ATI Radeon X850 SE (R480), ATI Radeon X850 PRO (R480),
	ATI Radeon X850 XT PE (R480), ATI Radeon Mobility M7,
	ATI Mobility FireGL 7800 M7, ATI Radeon Mobility M6,
	ATI FireGL Mobility 9000 (M9), ATI Radeon Mobility 9000 (M9),
	ATI Radeon 9700 Pro, ATI Radeon 9700/9500Pro, ATI FireGL X1,
	ATI Radeon 9800PRO, ATI Radeon 9800XT,
	ATI Radeon Mobility 9600/9700 (M10/M11),
	ATI Radeon Mobility 9600 (M10), ATI Radeon Mobility 9600 (M11),
	ATI FireGL Mobility T2 (M10), ATI FireGL Mobility T2e (M11),
	ATI Radeon, ATI FireGL 8700/8800, ATI Radeon 8500, ATI Radeon 9100,
	ATI Radeon 7500, ATI Radeon VE/7000, ATI ES1000,
	ATI Radeon Mobility X300 (M22), ATI Radeon Mobility X600 SE (M24C),
	ATI FireGL M22 GL, ATI Radeon X800 (R423), ATI Radeon X800PRO (R423),
	ATI Radeon X800LE (R423), ATI Radeon X800SE (R423),
	ATI Radeon X800 XTP (R430), ATI Radeon X800 XL (R430),
	ATI Radeon X800 SE (R430), ATI Radeon X800 (R430),
	ATI FireGL V7100 (R423), ATI FireGL V5100 (R423),
	ATI FireGL unknown (R423), ATI Mobility FireGL V5000 (M26),
	ATI Mobility Radeon X700 XL (M26), ATI Mobility Radeon X700 (M26),
	ATI Radeon X550XTX, ATI Radeon 9100 IGP (A5),
	ATI Radeon Mobility 9100 IGP (U3), ATI Radeon XPRESS 200,
	ATI Radeon XPRESS 200M, ATI Radeon 9250, ATI Radeon 9200,
	ATI Radeon 9200SE, ATI FireMV 2200, ATI Radeon X300 (RV370),
	ATI Radeon X600 (RV370), ATI Radeon X550 (RV370),
	ATI FireGL V3100 (RV370), ATI FireMV 2200 PCIE (RV370),
	ATI Radeon Mobility 9200 (M9+), ATI Mobility Radeon X800 XT (M28),
	ATI Mobility FireGL V5100 (M28), ATI Mobility Radeon X800 (M28),
	ATI Radeon X850, ATI unknown Radeon / FireGL (R480),
	ATI Radeon X800XT (R423), ATI FireGL V5000 (RV410),
	ATI Radeon X700 XT (RV410), ATI Radeon X700 PRO (RV410),
	ATI Radeon X700 SE (RV410), ATI Radeon X700 (RV410),
	ATI Radeon X1800, ATI Mobility Radeon X1800 XT,
	ATI Mobility Radeon X1800, ATI Mobility FireGL V7200,
	ATI FireGL V7200, ATI FireGL V5300, ATI Mobility FireGL V7100,
	ATI FireGL V7300, ATI FireGL V7350, ATI Radeon X1600, ATI RV505,
	ATI Radeon X1300/X1550, ATI Radeon X1550, ATI M54-GL,
	ATI Mobility Radeon X1400, ATI Radeon X1550 64-bit,
	ATI Mobility Radeon X1300, ATI Radeon X1300, ATI FireGL V3300,
	ATI FireGL V3350, ATI Mobility Radeon X1450,
	ATI Mobility Radeon X2300, ATI Mobility Radeon X1350,
	ATI FireMV 2250, ATI Radeon X1650, ATI Mobility FireGL V5200,
	ATI Mobility Radeon X1600, ATI Radeon X1300 XT/X1600 Pro,
	ATI FireGL V3400, ATI Mobility FireGL V5250,
	ATI Mobility Radeon X1700, ATI Mobility Radeon X1700 XT,
	ATI FireGL V5200, ATI Radeon X2300HD, ATI Mobility Radeon HD 2300,
	ATI Radeon X1950, ATI Radeon X1900, ATI AMD Stream Processor,
	ATI RV560, ATI Mobility Radeon X1900, ATI Radeon X1950 GT, ATI RV570,
	ATI FireGL V7400, ATI Radeon 9100 PRO IGP,
	ATI Radeon Mobility 9200 IGP, ATI Radeon X1200, ATI RS740,
	ATI RS740M, ATI Radeon HD 2900 XT, ATI Radeon HD 2900 Pro,
	ATI Radeon HD 2900 GT, ATI FireGL V8650, ATI FireGL V8600,
	ATI FireGL V7600, ATI Radeon 4800 Series, ATI Radeon HD 4870 x2,
	ATI Radeon HD 4850 x2, ATI FirePro V8750 (FireGL),
	ATI FirePro V7760 (FireGL), ATI Mobility RADEON HD 4850,
	ATI Mobility RADEON HD 4850 X2, ATI FirePro RV770,
	AMD FireStream 9270, AMD FireStream 9250, ATI FirePro V8700 (FireGL),
	ATI Mobility RADEON HD 4870, ATI Mobility RADEON M98,
	ATI FirePro M7750, ATI M98, ATI Mobility Radeon HD 4650,
	ATI Radeon RV730 (AGP), ATI Mobility Radeon HD 4670,
	ATI FirePro M5750, ATI RV730XT [Radeon HD 4670], ATI RADEON E4600,
	ATI Radeon HD 4600 Series, ATI RV730 PRO [Radeon HD 4650],
	ATI FirePro V7750 (FireGL), ATI FirePro V5700 (FireGL),
	ATI FirePro V3750 (FireGL), ATI Mobility Radeon HD 4830,
	ATI Mobility Radeon HD 4850, ATI FirePro M7740, ATI RV740,
	ATI Radeon HD 4770, ATI Radeon HD 4700 Series, ATI RV610,
	ATI Radeon HD 2400 XT, ATI Radeon HD 2400 Pro,
	ATI Radeon HD 2400 PRO AGP, ATI FireGL V4000, ATI Radeon HD 2350,
	ATI Mobility Radeon HD 2400 XT, ATI Mobility Radeon HD 2400,
	ATI RADEON E2400, ATI FireMV 2260, ATI RV670, ATI Radeon HD3870,
	ATI Mobility Radeon HD 3850, ATI Radeon HD3850,
	ATI Mobility Radeon HD 3850 X2, ATI Mobility Radeon HD 3870,
	ATI Mobility Radeon HD 3870 X2, ATI Radeon HD3870 X2,
	ATI FireGL V7700, ATI Radeon HD3690, AMD Firestream 9170,
	ATI Radeon HD 4550, ATI Radeon RV710, ATI Radeon HD 4350,
	ATI Mobility Radeon 4300 Series, ATI Mobility Radeon 4500 Series,
	ATI FirePro RG220, ATI Mobility Radeon 4330, ATI RV630,
	ATI Mobility Radeon HD 2600, ATI Mobility Radeon HD 2600 XT,
	ATI Radeon HD 2600 XT AGP, ATI Radeon HD 2600 Pro AGP,
	ATI Radeon HD 2600 XT, ATI Radeon HD 2600 Pro, ATI Gemini RV630,
	ATI Gemini Mobility Radeon HD 2600 XT, ATI FireGL V5600,
	ATI FireGL V3600, ATI Radeon HD 2600 LE,
	ATI Mobility FireGL Graphics Processor, ATI Radeon HD 3470,
	ATI Mobility Radeon HD 3430, ATI Mobility Radeon HD 3400 Series,
	ATI Radeon HD 3450, ATI Radeon HD 3430, ATI FirePro V3700,
	ATI FireMV 2450, ATI Radeon HD 3600 Series, ATI Radeon HD 3650 AGP,
	ATI Radeon HD 3600 PRO, ATI Radeon HD 3600 XT,
	ATI Mobility Radeon HD 3650, ATI Mobility Radeon HD 3670,
	ATI Mobility FireGL V5700, ATI Mobility FireGL V5725,
	ATI Radeon HD 3200 Graphics, ATI Radeon 3100 Graphics,
	ATI Radeon HD 3300 Graphics, ATI Radeon 3000 Graphics, SUMO, SUMO2,
	ATI Radeon HD 4200, ATI Radeon 4100, ATI Mobility Radeon HD 4200,
	ATI Mobility Radeon 4100, ATI Radeon HD 4290, ATI Radeon HD 4250,
	AMD Radeon HD 6310 Graphics, AMD Radeon HD 6250 Graphics,
	AMD Radeon HD 6300 Series Graphics,
	AMD Radeon HD 6200 Series Graphics, PALM, CYPRESS,
	ATI FirePro (FireGL) Graphics Adapter, AMD Firestream 9370,
	AMD Firestream 9350, ATI Radeon HD 5800 Series,
	ATI Radeon HD 5900 Series, ATI Mobility Radeon HD 5800 Series,
	ATI Radeon HD 5700 Series, ATI Radeon HD 6700 Series,
	ATI Mobility Radeon HD 5000 Series, ATI Mobility Radeon HD 5570,
	ATI Radeon HD 5670, ATI Radeon HD 5570, ATI Radeon HD 5500 Series,
	REDWOOD, ATI Mobility Radeon Graphics, CEDAR, ATI FirePro 2270,
	ATI Radeon HD 5450, CAYMAN, AMD Radeon HD 6900 Series,
	AMD Radeon HD 6900M Series, Mobility Radeon HD 6000 Series, BARTS,
	AMD Radeon HD 6800 Series, AMD Radeon HD 6700 Series, TURKS, CAICOS,
	ARUBA, TAHITI, PITCAIRN, VERDE, OLAND, HAINAN, BONAIRE, KABINI,
	MULLINS, KAVERI, HAWAII
[  1388.075] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  1388.075] (++) using VT number 2

[  1388.076] (II) [KMS] Kernel modesetting enabled.
[  1388.077] (WW) Falling back to old probe method for modesetting
[  1388.082] (II) RADEON(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[  1388.082] (==) RADEON(0): Depth 24, (--) framebuffer bpp 32
[  1388.082] (II) RADEON(0): Pixel depth = 24 bits stored in 4 bytes (32 bpp pixmaps)
[  1388.082] (==) RADEON(0): Default visual is TrueColor
[  1388.082] (II) Applying OutputClass "Radeon" options to /dev/dri/card0
[  1388.082] (**) RADEON(0): Option "Accel" "false"
[  1388.083] (==) RADEON(0): RGB weight 888
[  1388.083] (II) RADEON(0): Using 8 bits per RGB (8 bit DAC)
[  1388.083] (--) RADEON(0): Chipset: "ATI Radeon Mobility M7" (ChipID = 0x4c57)
[  1388.083] (II) Loading sub module "fb"
[  1388.083] (II) LoadModule: "fb"
[  1388.085] (II) Loading /usr/lib/xorg/modules/libfb.so
[  1388.090] (II) Module fb: vendor="X.Org Foundation"
[  1388.091] 	compiled for 1.20.6, module version = 1.0.0
[  1388.091] 	ABI class: X.Org ANSI C Emulation, version 0.4
[  1388.091] (II) RADEON(0): GPU accel disabled or not working, using shadowfb for KMS
[  1388.091] (II) Loading sub module "shadow"
[  1388.091] (II) LoadModule: "shadow"
[  1388.092] (II) Loading /usr/lib/xorg/modules/libshadow.so
[  1388.096] (II) Module shadow: vendor="X.Org Foundation"
[  1388.096] 	compiled for 1.20.6, module version = 1.1.0
[  1388.097] 	ABI class: X.Org ANSI C Emulation, version 0.4
[  1388.097] (II) RADEON(0): KMS Color Tiling: disabled
[  1388.097] (II) RADEON(0): KMS Color Tiling 2D: disabled
[  1388.097] (II) RADEON(0): KMS Pageflipping: enabled
[  1388.097] (II) RADEON(0): SwapBuffers wait for vsync: enabled
[  1388.098] (II) RADEON(0): Output LVDS has no monitor section
[  1388.109] (II) RADEON(0): Output VGA-0 has no monitor section
[  1388.112] (II) RADEON(0): Output S-video has no monitor section
[  1388.113] (WW) RADEON(0): 3 ZaphodHeads crtcs unavailable. Some outputs will stay off.
[  1388.113] (II) RADEON(0): EDID for output LVDS
[  1388.113] (II) RADEON(0): Manufacturer: APP  Model: 9c1a  Serial#: 0
[  1388.113] (II) RADEON(0): Year: 2001  Week: 31
[  1388.114] (II) RADEON(0): EDID Version: 1.3
[  1388.114] (II) RADEON(0): Digital Display Input
[  1388.114] (II) RADEON(0): Max Image Size [cm]: horiz.: 29  vert.: 21
[  1388.114] (II) RADEON(0): Gamma: 2.20
[  1388.114] (II) RADEON(0): No DPMS capabilities specified
[  1388.114] (II) RADEON(0): Supported color encodings: RGB 4:4:4 YCrCb 4:4:4 
[  1388.114] (II) RADEON(0): First detailed timing not preferred mode in violation of standard!
[  1388.114] (II) RADEON(0): redX: 0.580 redY: 0.339   greenX: 0.327 greenY: 0.533
[  1388.114] (II) RADEON(0): blueX: 0.157 blueY: 0.143   whiteX: 0.320 whiteY: 0.330
[  1388.114] (II) RADEON(0): Supported established timings:
[  1388.115] (II) RADEON(0): 1024x768@60Hz
[  1388.115] (II) RADEON(0): Manufacturer's mask: 0
[  1388.115] (II) RADEON(0): Supported detailed timing:
[  1388.115] (II) RADEON(0): clock: 65.0 MHz   Image Size:  285 x 214 mm
[  1388.115] (II) RADEON(0): h_active: 1024  h_sync: 1048  h_sync_end 1184 h_blank_end 1344 h_border: 0
[  1388.115] (II) RADEON(0): v_active: 768  v_sync: 771  v_sync_end 777 v_blanking: 806 v_border: 0
[  1388.115] (II) RADEON(0):  LTN141XF
[  1388.115] (II) RADEON(0):  LTN141XF
[  1388.115] (II) RADEON(0): Monitor name: Color LCD
[  1388.115] (II) RADEON(0): EDID (in hex):
[  1388.115] (II) RADEON(0): 	00ffffffffffff0006101a9c00000000
[  1388.116] (II) RADEON(0): 	1f0b0103801d157808be629456538828
[  1388.116] (II) RADEON(0): 	24525400080001010101010101010101
[  1388.116] (II) RADEON(0): 	01010101010164190040410026301888
[  1388.116] (II) RADEON(0): 	36001dd610000018000000fe004c544e
[  1388.116] (II) RADEON(0): 	31343158460000000a20000000fe004c
[  1388.116] (II) RADEON(0): 	544e31343158460000000a20000000fc
[  1388.116] (II) RADEON(0): 	00436f6c6f72204c43440a20202000ba
[  1388.116] (II) RADEON(0): Printing probed modes for output LVDS
[  1388.117] (II) RADEON(0): Modeline "1024x768"x60.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
[  1388.117] (II) RADEON(0): Modeline "800x600"x60.0   38.31  800 832 912 1024  600 603 607 624 -hsync +vsync (37.4 kHz)
[  1388.117] (II) RADEON(0): Modeline "848x480"x59.9   31.65  848 872 952 1056  480 483 493 500 -hsync +vsync (30.0 kHz)
[  1388.117] (II) RADEON(0): Modeline "720x480"x59.9   26.85  720 744 808 896  480 483 493 500 -hsync +vsync (30.0 kHz)
[  1388.117] (II) RADEON(0): Modeline "640x480"x59.9   23.98  640 664 720 800  480 483 487 500 -hsync +vsync (30.0 kHz)
[  1388.128] (II) RADEON(0): EDID for output VGA-0
[  1388.131] (II) RADEON(0): EDID for output S-video
[  1388.131] (II) RADEON(0): Output LVDS connected
[  1388.131] (II) RADEON(0): Output VGA-0 disconnected
[  1388.131] (II) RADEON(0): Output S-video disconnected
[  1388.131] (II) RADEON(0): Using exact sizes for initial modes
[  1388.131] (II) RADEON(0): Output LVDS using initial mode 1024x768 +0+0
[  1388.132] (II) RADEON(0): mem size init: gart size :1fdff000 vram size: s:2000000 visible:3e40000
[  1388.132] (II) RADEON(0): EXA: Driver will allow EXA pixmaps in VRAM
[  1388.132] (==) RADEON(0): DPI set to (96, 96)
[  1388.132] (==) RADEON(0): Using gamma correction (1.0, 1.0, 1.0)
[  1388.132] (II) Loading sub module "ramdac"
[  1388.132] (II) LoadModule: "ramdac"
[  1388.132] (II) Module "ramdac" already built-in
[  1388.132] (II) UnloadModule: "modesetting"
[  1388.133] (II) Unloading modesetting
[  1388.134] (II) RADEON(0): Front buffer size: 3072K
[  1388.135] (II) RADEON(0): VRAM usage limit set to 54576K
[  1388.146] (==) RADEON(0): DRI3 disabled
[  1388.146] (==) RADEON(0): Backing store enabled
[  1388.146] (WW) RADEON(0): Direct rendering disabled
[  1388.146] (II) RADEON(0): Acceleration disabled
[  1388.147] (==) RADEON(0): DPMS enabled
[  1388.147] (==) RADEON(0): Silken mouse disabled
[  1388.153] (II) Initializing extension Generic Event Extension
[  1388.155] (II) Initializing extension SHAPE
[  1388.156] (II) Initializing extension MIT-SHM
[  1388.157] (II) Initializing extension XInputExtension
[  1388.163] (II) Initializing extension XTEST
[  1388.164] (II) Initializing extension BIG-REQUESTS
[  1388.166] (II) Initializing extension SYNC
[  1388.169] (II) Initializing extension XKEYBOARD
[  1388.174] (II) Initializing extension XC-MISC
[  1388.175] (II) Initializing extension SECURITY
[  1388.176] (II) Initializing extension XFIXES
[  1388.177] (II) Initializing extension RENDER
[  1388.178] (II) Initializing extension RANDR
[  1388.181] (II) Initializing extension COMPOSITE
[  1388.182] (II) Initializing extension DAMAGE
[  1388.183] (II) Initializing extension MIT-SCREEN-SAVER
[  1388.184] (II) Initializing extension DOUBLE-BUFFER
[  1388.185] (II) Initializing extension RECORD
[  1388.186] (II) Initializing extension DPMS
[  1388.187] (II) Initializing extension Present
[  1388.188] (II) Initializing extension DRI3
[  1388.189] (II) Initializing extension X-Resource
[  1388.190] (II) Initializing extension XVideo
[  1388.191] (II) Initializing extension XVideo-MotionCompensation
[  1388.191] (II) Initializing extension GLX
[  1388.192] (II) AIGLX: Screen 0 is not DRI2 capable
[  1389.938] (II) IGLX: Loaded and initialized swrast
[  1389.938] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[  1389.938] (II) Initializing extension XFree86-VidModeExtension
[  1389.940] (II) Initializing extension XFree86-DGA
[  1389.941] (II) Initializing extension XFree86-DRI
[  1389.941] (II) Initializing extension DRI2
[  1389.945] (II) RADEON(0): Setting screen physical size to 270 x 203

**Comment by nicolascolla** [comment]
Steps to reproduce:

-Edit /usr/share/X11/xorg.conf.d/10-radeon.conf
-Add the following line:
Option "NoAccel" "true"
-Run startx

**Comment by q66** [comment]
this means you have a KMS driver, so why bother with radeon at all, instead of using modesetting? (you should also be able to get fbdev + xf86-video-fbdev working by disabling modeset and falling back to dumb framebuffer, and have functional suspend/resume)

**Comment by q66** [comment]
Also, confirmed the lockup on a 2004 PowerBook G4.

However, using

```
Section "Device"
    Identifier "GPU0"
    Driver "fbdev"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "GPU0"
EndSection
```

works just fine; no need to mess with anything.

**Comment by q66** [comment]
Fixed: https://github.com/void-linux/void-packages/commit/0f0a5a52b94ecf6093fb2ca412c1df99fb9ee05b
