### ISSUE TITLE
ppc64: linux5.5 fails to detect SATA controller on pci

### ISSUE THREAD

**Issue by pullmoll** [void-ppc/void-packages#37]
I compiled linux5.5-5.5.5 for ppc64 and it boots ok. Yet it fails to recognize my SATA controller, JMB363 SATA/IDE controller manufactured by JMicron Technology Corp. pci197b,2363, and thus fails to detect an 1TB SSD attached to it.

I put this extra controller in my G5 because the internal K2 SATA manufactured by Broadcom doesn't work with newer SSDs.

The controller is recognized in linux5.4 so I think some configuration option dealing with the PCI bus may prevent its detection / enumeration.

Here's the lspci output on linux5.4-5.4.21_1:
```
0001:09:00.0 SATA controller: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 01 [AHCI 1.0])
	Subsystem: JMicron Technology Corp. JMB363 SATA/IDE Controller
	Device tree node: /sys/firmware/devicetree/base/ht@0,f2000000/pci@6/pci197b,2363@0
	Flags: bus master, fast devsel, latency 0, IRQ 62
	Memory at 80100000 (32-bit, non-prefetchable) [size=8K]
	Expansion ROM at 80110000 [disabled] [size=64K]
	Capabilities: [68] Power Management version 2
	Capabilities: [50] Express Legacy Endpoint, MSI 01
	Kernel driver in use: ahci
```

Any ideas what I could try to change?

**Comment by pullmoll** [comment]
It seems I found the change. In linux5.4 there were options
```
CONFIG_PCIE_CADENCE=y
CONFIG_PCIE_CADENCE_HOST=y
CONFIG_PCIE_CADENCE_EP=y
```
in linux5.5 these were renamed to
```
CONFIG_PCIE_CADENCE_PLAT_HOST=y
CONFIG_PCIE_CADENCE_PLAT_EP=y
```
I pushed the modified `ppc64-dotconfig` file. I not confident whether this should be changed for `ppc64le-dotconfig` as well, while I believe it should to match the previous configuration. I'll leave that to you @q66.

**Comment by q66** [comment]
please enable for ppc64le as well, thanks

**Comment by pullmoll** [comment]
Done.
