### ISSUE TITLE
Arctic-fox as an altenative web browser for ppc 32-bit?

### ISSUE THREAD

**Issue by truscellino** [void-ppc/void-packages#38]
Hi,
given that Firefox is troublesome on ppc 32 bits, I wonder if arctic-fox could be offered as an alternative? I think it does include code from Pale Moon as well as ppc tweaks from Tenfourfox. But I am no developer so I can't check any of these statements...
[Arctic-fox](https://github.com/wicknix/Arctic-Fox)
Thanks

**Comment by HadetTheUndying** [comment]
I can confirm that the prebuilt binaries work fine. I have not tried to compile from source though. So long as all the dependencies are available it shouldn't be a problem to throw a template together though. I'll probably have time to mess around with this this weekend.

**Comment by truscellino** [comment]
Interesting. Thanks.

**Comment by q66** [comment]
apparently it only compiles with gcc6 at most, so that's a problem

**Comment by HadetTheUndying** [comment]
Yeah i think best case scenario would setting up a template for people to manually package the pre-built binaries and including it in the doc, as an option other than epiphany. It does run faster, but not being able to build it is a frustration.

**Comment by q66** [comment]
nah, if people want the prebuilt binaries they can just fetch it and run it themselves, no point in cluttering the repo with it

**Comment by FabriceColin** [comment]
Is there tool (in a similar spirit to Debian's alien) that would convert the ArticFox .deb package into a xbps package suitable for Void?

**Comment by HadetTheUndying** [comment]
@FabriceColin it should be pretty easy to write your own srcpkg for

**Comment by wicknix** [comment]
2 simple solutions. Install voids minimal gcc6 package to build Arctic Fox. It's been tested and works. Otherwise just xbps-install dpkg. Then just run: sudo dpkg -i /path/to/arcticfox.deb to install. It will create a menu entry and install to /usr/lib/arcticfox just like it does on ubuntu/debian.

**Comment by q66** [comment]
both are terrible ideas, the "minimal gcc6" exists purely for java bootstrap and isn't configured for correct C/C++ builds, and you should *never* install packages with dpkg directly on non-debian systems, it can badly mess up your system

if you want to install programs from deb packages, unpack them manually

**Comment by wicknix** [comment]
Then why is dpkg in voids repo? All dpkg does is unpack the .deb and place the files where they need to be. Also more people than just myself have confirmed gcc6 in voids repo properly builds AF. Like it or not, these solutions work.

**Comment by HadetTheUndying** [comment]
> Then why is dpkg in voids repo? All dpkg does is unpack the .deb and place the files where they need to be. Also more people than just myself have confirmed gcc6 in voids repo properly builds AF. Like it or not, these solutions work.

Void has a number of package managers in the repo for handling extracting packages and bootstrap installations. None of them are meant for installing packages.

**Comment by q66** [comment]
here's an idea: just fix builds with actual modern compilers

**Comment by wicknix** [comment]
Be my guest. Everybody wants stuff, but nobody bothers to help. You know how that goes. At any rate, the 32-bit AF .debs are self contained binary archives. Other than a .png and a .desktop file, everything else stays in the /arcticfox directory. It's not like using dpkg for this will overwrite any xbps installed packages or system files, so i don't see how it could mess anything up. As for the incomplete gcc6... i've been running AF built on void64 for a few months now with no issue. Argue it all you want, but the fact is it's stable. All i'm trying to do is offer up some extra browsers because short of color blind quantum, all the other graphical browsers have issues. Forgive me for wanting to give people some other options.
