### ISSUE TITLE
appletouch touchpad non-responsive on linux5.8

### ISSUE THREAD

**Issue by retronica** [void-ppc/void-packages#43]
### System

* xuname:  
  ``Void 5.8.8_1 ppc PowerMac uptodate FF``
* package:  
  *affected package(s) including the version*: ``linux5.8-5.8.8_1`` (but also other 5.8 series)
* device:  
  PowerBook G4 1.5GHz (PowerBook6,8). 
  Touchpad is the inbuilt touchpad detected by the system as "appletouch"
### Expected behavior
``dmesg | grep appletouch`` from booting using linux5.4-5.4.64_1:
``[16.750986] input appletouch as /devices/pci0001:10/0001:10:1a.0/usb2/2-2/2-2:1.0/input/input5``
``[16.802967] usbcore: registered new interface driver appletouch``
Touchpad works normally
### Actual behavior
``dmesg | grep appletouch`` from booting using linux5.8-5.8.8_1:
``[16.992741] input appletouch as /devices/pci0001:10/0001:10:1a.0/usb2/2-2/2-2:1.0/input/input8``
``[17.028812] usbcore: registered new interface driver appletouch``
``[17.045798] appletouch 2-2:1.0: input: appletouch disconnected``
``[17.046998] input appletouch as /devices/pci0001:10/0001:10:1a.0/usb2/2-2/2-2:1.0/input/input10``
Touchpad ends up completely non-responsive
### Steps to reproduce the behavior
Boot device using linux5.8 kernel (linux5.4 and linux4.4 [at least] work as expected)

**Comment by q66** [comment]
can you test 5.9?

**Comment by retronica** [comment]
Normally functionality appears to be restored in 5.9.
