### ISSUE TITLE
OpenBLAS on PPC970

### ISSUE THREAD

**Issue by super-cow-powers** [void-ppc/void-packages#47]
Right now, OpenBLAS is (fairly reasonably) being built for P6 upwards, but this gives occasional issues with running into Illegal Instructions on (at least) the 970. I rebuilt with target as 970MP and it works but is then not optimised for newer chips.
Trying a dynamic build with target as 970MP fails at: 
make[1]: *** No rule to make target 'dgemm_incopy_POWER10.o', needed by 'kernel'.  Stop.

**Comment by q66** [comment]
as far as i can tell, openblas ppc64 support is power6+ only

**Comment by super-cow-powers** [comment]
That's definitely possible, but everything back to P4 is on the supported target list. I'm guessing it came through from GotoBLAS.
https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt

**Comment by q66** [comment]
this is addressed in upcoming packages, we now default to 970MP
