### ISSUE TITLE
grep -P causes illegal instruction on iBook G3 (PowerBook4,1)

### ISSUE THREAD

**Issue by mahiuchun** [void-ppc/void-packages#53]
### System

* xuname:  
  Vod 5.10.67_1 ppc PowerMac uptodate FFF
* package:  
  pcre-8.45_1

### Expected behavior
grep waits for input from stdin.

### Actual behavior
Illegal instruction

### Steps to reproduce the behavior
`grep -P '.*'`

**Comment by q66** [comment]
does this still happen?

**Comment by mahiuchun** [comment]
No longer happens after latest update, thanks!
