### ISSUE TITLE
Error starting pulseview

### ISSUE THREAD

**Issue by chmeeedalf** [void-ppc/void-packages#54]
### System

* xuname:  
 Void 5.15.9_1 ppc64le PowerNV uptodate FFF

* package:  
  libsigrokdecode-0.5.3_4
  pulseview-0.4.2_1

### Expected behavior
  pulseview starts up

### Actual behavior
pulseview: symbol lookup error: /usr/lib64/libsigrokdecode.so.4: undefined symbol: _Py_NoneStruct

### Steps to reproduce the behavior
Install pulseview on ppc64le and run it from a terminal.

From what I can find from a web search this is due to either pulseview or libsigrokdecode not linking against libpython.

I'm unable to confirm on void x86, as I don't have an x86 machine to test with.

**Comment by q66** [comment]
this got fixed a while ago
