### ISSUE TITLE
xbps-install curl fails to download.

### ISSUE THREAD

**Issue by pk2061** [void-ppc/void-packages#63]
Hi,
I hope I am posting my problem at the right place:
I am running VoidLinunx PPC on my iMac G3.
I was trying to install curl as shown below:
[root@imacg3linux jan]# xbps-install curl

Name Action    Version           New version            Download size
curl install   -                 7.81.0_2               205KB 

Size to download:              206KB
Size required on disk:         476KB
Space available on disk:       9.9GB

Do you want to continue? [Y/n] y

[*] Downloading packages
ERROR: [trans] failed to download `curl-7.81.0_2' signature from `https://auto.voidlinux-ppc.org/current/ppc': Not Found
Transaction failed! see above for errors.
[root@imacg3linux jan]# xuname
bash: xuname: command not found
[root@imacg3linux jan]# 

It seems that the package is missing? 
What can I do to fix this problem?

Thanks in advance for your help!
Best regards
Jan

**Comment by q66** [comment]
you haven't synced your package database/index
