### ISSUE TITLE
Toolchain bootstrap support

### ISSUE THREAD

**Issue by q66** [void-ppc/void-packages#7]
This is to serve as a reference for what languages fully support proper binary host bootstrap from all of our `ppc64` targets.

- [x] Rust
- [x] Nim
- [x] Go (only 64-bit LE supported)
- [x] Java
- [ ] D (ldc; needs dmd to bootstrap in current template, dmd is x86 only)
- [x] Haskell 
- [ ] Common Lisp (sbcl; no BE for now)
- TBD

**Comment by trommler** [comment]
I am working on ghc (Haskell) for ppc64 (BE), glibc. See #55.

**Comment by trommler** [comment]
The necessary fix for ghc on ppc64 is in PR #56.

**Comment by q66** [comment]
there is no point in tracking this any further, closing
