### ISSUE TITLE
qemu-user-static: update to 4.0.0 broke it for ppc64-musl

### ISSUE THREAD

**Issue by pullmoll** [void-ppc/void-packages#9]
Oops, sorry, updating qemu-user-static to 4.0.0 broke it for `ppc64-musl` because musl libc does not define register indices like `PT_NIP` which `linux-user/host/ppc64/hostdep.h` now expects to be defined.

Also `uc_mcontext.regs->reg_name` is not defined because `uc_mcontext.regs` is an opaque `void *`.
This needs some patching which updating to `qemu-4.0.0` will need as well.

**Comment by q66** [comment]
Well, with musl there are two definitions of `pt_regs` in two places, most things can be patched... no big deal

**Comment by q66** [comment]
fixed
